# Generated by Django 6.0.2 on 2026-02-27 13:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='projects',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('code', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Visible text, ej: Demo, Code, API'}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide icon name, ej: github, external-link', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('icon', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='description',
            field=models.TextField(help_text='Short description for previews'),
        ),
    ]
