# Generated by Django 6.0.2 on 2026-02-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_featured_projects_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='social_links',
        ),
    ]
