# Generated by Django 6.0.2 on 2026-02-27 02:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_content'),
        ('projects', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.projectpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_role',
            field=models.CharField(blank=True, help_text='Your occupation', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Your name', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_links',
            field=wagtail.fields.StreamField([('abc', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Social name (e.g. GitHub)'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide icon name (e.g. github, linkedin, twitter)'}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1), ('url', 2)]], {})}),
        ),
    ]
